### ISSUE TITLE
Foundation issue

### ISSUE THREAD

**Issue by nigels0** [LukeSpad/BeoGateway#1]
I’ve installed Foundation library, but have this issue:

`pi@domoticzpi:~/domoticz/progs/BeoGateway$ pip install Foundation
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: Foundation in /home/pi/.local/lib/python2.7/site-packages (0.1.0a0.dev1)
Requirement already satisfied: django-sekizai>=0.10 in /home/pi/.local/lib/python2.7/site-packages (from Foundation) (2.0.0)
Requirement already satisfied: Django<1.11,>=1.10 in /home/pi/.local/lib/python2.7/site-packages (from Foundation) (1.10.8)
Requirement already satisfied: django-classy-tags>=1 in /home/pi/.local/lib/python2.7/site-packages (from django-sekizai>=0.10->Foundation) (2.0.0)

pi@domoticzpi:~/domoticz/progs/BeoGateway$ python main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import Resources.ASBridge as ASBridge
  File "/home/pi/domoticz/progs/BeoGateway/Resources/ASBridge.py", line 3, in <module>
    from Foundation import NSAppleScript
ImportError: No module named Foundation’

**Comment by LukeSpad** [comment]
Hi there,

Are you attempting to run in a pc or a Mac? I’m afraid the application is Mac only:

The ASBridge module contains the Apple Scripting Bridge implementation to control Apple Music. It requires two Apple specific libraries that are included as part of the standard python build on a Mac. 

If you are running on a Mac then check to see that those libraries are installed and up to date - they should be there right out of the box?

L

**Comment by nigels0** [comment]
Actually on a raspberry. Explains the issue. 

Really I’ll need to cut out all the Mac specific stuff. All I really want is to monitor the ML commands to allow me to power a screen on and off. 

Regards

**Comment by LukeSpad** [comment]
No worries - in that case just edit the callback function cb() to remove everything except the message reporting. Everything else is system agnostic 👍

**Comment by nigels0** [comment]
Thanks.
