### ISSUE TITLE
Where do you configure the plugin in Indigo?

### ISSUE THREAD

**Issue by axdero** [LukeSpad/BeoGateway#2]
Hello,
Maybe it's a silly question but I do not find where to configure the plugin in Indigo (as stated in step 2 of the installation process).
In the Indigo "Plugins/BeoGateway Plugin" menu I've only got items like Disable, Reload, Reload in debugger,... nothing to configure the plugin itself (see attached screenshot).
Could you please help me?
Best regards,
Axel
![BeoGateway Plugin Menu](https://user-images.githubusercontent.com/82722620/167252117-de1b4d41-8cc3-421c-87cc-9a63ea91fd85.jpg)
l

**Comment by LukeSpad** [comment]
Dear Axel,

Please find attached an updated version of the plugin - please be aware there is still some work to be done to sort out the initialisation process but once the plugin is up and running everything should be fine. As I say I’ll issue an update when the new version of Indigo releases in a couple of weeks.

For now, if you install this version of the plugin then a configuration menu will pop up when you start the plugin. Once configured you’re going to see a lot of errors in the log - simply restart the plugin and everything should be fine. As I say I’m working to resolve the startup issues (which will be a relatively simple fix) but I’ve been holding off publishing a new version until the new version of indigo ships (as I’ll need to make a few additional changes at that point).

With best wishes
Luke

**Comment by axdero** [comment]
Dear Luke,
Thanks for quick and positive answer.
I will try the updated version and come back to you with the results.
I hope that I will be able to help you a little before your next release of this very promising plug in.
One small question though: I do not see the attached version you are talking about (sorry I'm a newbie on GitHub).
Have a nice weekend.
Best regards,
Axel

**Comment by LukeSpad** [comment]
Hi Axel - you can find the updated BeoGateway.indigoPlugin.zip in the https://github.com/LukeSpad/BeoGateway <https://github.com/LukeSpad/BeoGateway> folder

**Comment by axdero** [comment]
Hi Luke, 
I had the time today to uninstall your plugin from Indigo and to reinstall the new version you have uploaded yesterday.
This time I was able to configure the plugin without trouble.
Unfortunately I still get an error when enabling the plugin:

   Starting plugin "BeoGateway Plugin 1.0.0" (pid 24941)
   Started plugin "BeoGateway Plugin 1.0.0"
   BeoGateway Plugin               Startup called
   BeoGateway Plugin Warning       Downloading configuration data from Gateway...
   BeoGateway Plugin Warning       Processing Gateway configuration data...

   BeoGateway Plugin Error         Error in plugin execution startup:

Traceback (most recent call last):
  File "plugin.py", line 1284, in startup
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.2/Plugins/BeoGateway indigoPlugin.indigoPlugin/Contents/Server Plugin/Resources/MLCONFIG.py", line 21, in __init__
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.2/Plugins/BeoGateway indigoPlugin.indigoPlugin/Contents/Server Plugin/Resources/MLCONFIG.py", line 39, in _download_data
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.2/Plugins/BeoGateway indigoPlugin.indigoPlugin/Contents/Server Plugin/Resources/MLCONFIG.py", line 193, in configure_mlgw
KeyError: 'Zone'

   BeoGateway Plugin Error         Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 1329, in runConcurrentThread
AttributeError: 'Plugin' object has no attribute 'mlgw'

   BeoGateway Plugin Error         plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)


I think that it should help you to know that I'm using a MLGW at home (not a BLGW) so no zoning concept for me.
I'm not in a hurry at all to get it working so please take your time and enjoy your Sunday.
Best regards,
Axel

**Comment by LukeSpad** [comment]
Hi Axel - have you tried restarting the plug-in?

**Comment by axdero** [comment]
Hello Luke,
Yes, I've restarted the plugin several times. I have also restarted Indigo. 
I've disabled and removed all the files linked to your plugin then I have reinstalled again this version. 
I've done the same with the previous version (1.1.0 - big package with all the B&O documentation inside) just to be sure. It's not working either - same error (AttributeError: 'Plugin' object has no attribute 'mlgw').
I've checked and tried to modify MLCONFIG.py, MLGW_CLIENT.py and plugin.py without any luck.
My next move will be to add some comments with meaningful output to appear in the Event Log at key moments of the plugin execution. 
By the way I'm running the latest version of Indigo.
Best regards,
Axel

**Comment by axdero** [comment]
Hello Luke,
I have found and corrected the problem, it was caused by a missing declaration in the MLCONFIG.py file.
I have added a new line in the "# Loop over the config data to find the rooms, devices and sources in the installation" section:
Line 107: room['Zone'] = 'NA' #AXEL

I've added my name as a comment so you can find it easily.
I'm attaching the modified version of MLCONFIG.py file.

Now everything is working correctly for me.
One last remark though: the plugin does not support room or device names with accentuated characters (like in French). 
It generates an error: "BeoGateway Plugin Error         Invalid character > found in telegram: >_MLLOGONLINE Aborting!"

I hope that this can help make the plugin more robust.
Best regards,
Axel
[MLCONFIG.py.zip](https://github.com/LukeSpad/BeoGateway/files/8655772/MLCONFIG.py.zip)

**Comment by LukeSpad** [comment]
Latest version should fix this issue
